In [2]:
import requests
import pandas as pd
import json

"""  
# --- preparation ---
url = "https://api.sgu.se/oppnadata/mineralrattigheter/ogc/features/v1/collections"

response=requests.get(url)

# ---- successful? ---
print(response.status_code)
print(response.headers.get("Content-Type"))

if response.status_code == 200:
    print("Good to go!")

    data = response.json()

else:
    print("Problem!") 
"""

'  \n# --- preparation ---\nurl = "https://api.sgu.se/oppnadata/mineralrattigheter/ogc/features/v1/collections"\n\nresponse=requests.get(url)\n\n# ---- successful? ---\nprint(response.status_code)\nprint(response.headers.get("Content-Type"))\n\nif response.status_code == 200:\n    print("Good to go!")\n\n    data = response.json()\n\nelse:\n    print("Problem!") \n'

In [3]:
""" 
# --- Before doing anything, let's check the structure ---
print(json.dumps(data, indent=2))

# note: no ID as INT but a str
"""

" \n# --- Before doing anything, let's check the structure ---\nprint(json.dumps(data, indent=2))\n\n# note: no ID as INT but a str\n"

In [ ]:
""" 
# Confirming IDs and titles as per above
for coll in data["collections"]:
    print(f"{coll['id']:40}  {coll['title']}")
"""

' \n# Confirming IDs and titles as epr above\nfor coll in data["collections"]:\n    print(f"{coll[\'id\']:40}  {coll[\'title\']}")\n'

In [5]:
# Now that I have chosen the collection, I have commented with # all the above

collection = "ut-metaller-industrimineral-beviljade"   
url = f"https://api.sgu.se/oppnadata/mineralrattigheter/ogc/features/v1/collections/{collection}/items"

params = {
    "limit": 10,
    "f": "json"    
}

response=requests.get(url)

# ---- successful? ---
print(response.status_code)

if response.status_code == 200:
    print("OK!")

else:
    print("Problem!")

200
OK!

In [ ]:
# --- Convert to DataFrame ---
raw_data = response.json()
raw_data

In [7]:
# --- data info ---
print(raw_data.keys())

dict_keys(['type', 'features', 'numberMatched', 'numberReturned', 'timeStamp', 'links'])

In [8]:
# --- backup ---
import copy
raw_data_backup = copy.deepcopy(raw_data)

In [9]:
# --- Access direct to the data ---
df = pd.json_normalize(raw_data["features"])
df

,type,id,geometry_name,geometry.type,geometry.coordinates,properties.name,properties.licenceid,properties.diarynr,properties.area_ha,properties.appl_date,...,properties.mineral,properties.county,properties.municipal,properties.owners,properties.permitid,properties.permittype,properties.status,properties.export_date,properties.geom_area,properties.geom_length
0,Feature,ut-metaller-industrimineral-beviljade.101,geom,Polygon,"[[[15.62086114, 61.42015288], [15.63762983, 61...",Kringeltjärn nr 2002,2020:75,BS 200-447-2020,413.6150,2020-04-13Z,...,grafit,Gävleborgs län,Ovanåkers kommun,Woxna Graphite AB (100%),101,Undersökningstillstånd,Beviljad,2026-03-04Z,4.136150e+06,11940.334919
1,Feature,ut-metaller-industrimineral-beviljade.1082,geom,Polygon,"[[[14.22385964, 63.06965876], [14.28142836, 63...",Skallböle nr 1,2016:7,BS 200-1047-2015,783.9565,2015-10-15Z,...,molybden,Jämtlands län,"Åre kommun, Bergs kommun",Vanadis Battery Metals AB (100%),1082,Undersökningstillstånd,Beviljad,2026-03-04Z,7.839565e+06,14358.080301
2,Feature,ut-metaller-industrimineral-beviljade.1106,geom,Polygon,"[[[16.96776522, 60.95131672], [17.02419227, 60...",Bergby nr 6,2021:50,BS 200-304-2021,2440.5912,2021-04-22Z,...,"litium, tantal",Gävleborgs län,Gävle kommun,Bergby Lithium AB (100%),1106,Undersökningstillstånd,Beviljad,2026-03-04Z,2.440591e+07,29847.103720
3,Feature,ut-metaller-industrimineral-beviljade.1107,geom,Polygon,"[[[20.67505791, 65.00541833], [20.70710205, 64...",Lillkågeträsk nr 1,2019:96,BS 200-888-2019,628.3206,2019-08-13Z,...,"bly, guld, koppar, silver, zink",Västerbottens län,Skellefteå kommun,Elemental Exploration Scandinavia AB (100%),1107,Undersökningstillstånd,Beviljad,2026-03-04Z,6.283206e+06,12909.319537
4,Feature,ut-metaller-industrimineral-beviljade.1153,geom,Polygon,"[[[18.61690211, 65.12937427], [18.71831282, 65...",Ytterberg nr 2,2018:108,BS 200-449-2018,1726.2657,2018-05-29Z,...,"guld, koppar, silver, zink",Västerbottens län,Malå kommun,Minexp AB (100%),1153,Undersökningstillstånd,Beviljad,2026-03-04Z,1.726266e+07,35705.260879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,Feature,ut-metaller-industrimineral-beviljade.8665,geom,Polygon,"[[[19.16058012, 65.33874707], [19.30516653, 65...",Stöverberg nr 101,2026:47,BS 200-1879-2025,20838.5904,2025-12-30Z,...,"bly, guld, koppar, silver, zink","Västerbottens län, Norrbottens län","Malå kommun, Arvidsjaurs kommun",1478078 BC Ltd (100%),8665,Undersökningstillstånd,Beviljad,2026-03-04Z,2.083859e+08,88147.766732
823,Feature,ut-metaller-industrimineral-beviljade.934,geom,Polygon,"[[[14.56286044, 58.10941313], [14.56837542, 58...",Norra Kärr nr 1,2009:139,BS 200-829-2009,139.3812,2009-06-12Z,...,nefelinsyenit,"Östergötlands län, Jönköpings län","Ödeshögs kommun, Jönköpings kommun",GREENNA Mineral AB (100%),934,Undersökningstillstånd,Beviljad,2026-03-04Z,1.393812e+06,4821.958851
824,Feature,ut-metaller-industrimineral-beviljade.981,geom,Polygon,"[[[21.23732586, 65.63296628], [21.23915964, 65...",Klöverträsk nr 1001,2020:40,BS 200-1317-2019,1459.0196,2019-12-09Z,...,"guld, koppar, molybden, silver",Norrbottens län,"Älvsbyns kommun, Piteå kommun",Boliden Mineral AB (100%),981,Undersökningstillstånd,Beviljad,2026-03-04Z,1.459020e+07,15874.834937
825,Feature,ut-metaller-industrimineral-beviljade.985,geom,Polygon,"[[[20.43648518, 64.90956848], [20.52842996, 64...",Björkdal nr 34,2017:162,BS 200-728-2017,2520.1587,2017-09-01Z,...,guld,Västerbottens län,Skellefteå kommun,Björkdalsgruvan AB (100%),985,Undersökningstillstånd,Beviljad,2026-03-04Z,2.520159e+07,23341.174973
826,Feature,ut-metaller-industrimineral-beviljade.99,geom,Polygon,"[[[16.52135812, 59.96840529], [16.55184512, 59...",Jugansbo nr 1007,2020:110,BS 200-360-2020,1320.0703,2020-03-18Z,...,"bly, silver, zink",Västmanlands län,Sala kommun,Boliden Mineral AB (100%),99,Undersökningstillstånd,Beviljad,2026-03-04Z,1.320070e+07,20591.821873

In [10]:
# --- removing columns for simplicity ---
print(df.keys())

Index(['type', 'id', 'geometry_name', 'geometry.type', 'geometry.coordinates',
       'properties.name', 'properties.licenceid', 'properties.diarynr',
       'properties.area_ha', 'properties.appl_date', 'properties.dec_date',
       'properties.validfrom', 'properties.validto', 'properties.mineral',
       'properties.county', 'properties.municipal', 'properties.owners',
       'properties.permitid', 'properties.permittype', 'properties.status',
       'properties.export_date', 'properties.geom_area',
       'properties.geom_length'],
      dtype='str')

In [11]:
removed_columns = ["type","geometry_name","geometry.type", "geometry.coordinates","properties.diarynr","properties.status",
                  "properties.export_date", "properties.geom_area", "properties.geom_length"]

df_col_ok = df.drop(columns=removed_columns)
df_col_ok

,id,properties.name,properties.licenceid,properties.area_ha,properties.appl_date,properties.dec_date,properties.validfrom,properties.validto,properties.mineral,properties.county,properties.municipal,properties.owners,properties.permitid,properties.permittype
0,ut-metaller-industrimineral-beviljade.101,Kringeltjärn nr 2002,2020:75,413.6150,2020-04-13Z,2020-11-04Z,2020-11-04Z,2026-11-04Z,grafit,Gävleborgs län,Ovanåkers kommun,Woxna Graphite AB (100%),101,Undersökningstillstånd
1,ut-metaller-industrimineral-beviljade.1082,Skallböle nr 1,2016:7,783.9565,2015-10-15Z,2016-01-20Z,2016-01-20Z,2028-01-20Z,molybden,Jämtlands län,"Åre kommun, Bergs kommun",Vanadis Battery Metals AB (100%),1082,Undersökningstillstånd
2,ut-metaller-industrimineral-beviljade.1106,Bergby nr 6,2021:50,2440.5912,2021-04-22Z,2021-07-06Z,2021-07-06Z,2027-07-06Z,"litium, tantal",Gävleborgs län,Gävle kommun,Bergby Lithium AB (100%),1106,Undersökningstillstånd
3,ut-metaller-industrimineral-beviljade.1107,Lillkågeträsk nr 1,2019:96,628.3206,2019-08-13Z,2019-11-20Z,2019-11-20Z,2027-11-20Z,"bly, guld, koppar, silver, zink",Västerbottens län,Skellefteå kommun,Elemental Exploration Scandinavia AB (100%),1107,Undersökningstillstånd
4,ut-metaller-industrimineral-beviljade.1153,Ytterberg nr 2,2018:108,1726.2657,2018-05-29Z,2018-09-26Z,2018-09-26Z,2026-09-26Z,"guld, koppar, silver, zink",Västerbottens län,Malå kommun,Minexp AB (100%),1153,Undersökningstillstånd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822,ut-metaller-industrimineral-beviljade.8665,Stöverberg nr 101,2026:47,20838.5904,2025-12-30Z,2026-03-04Z,2026-03-04Z,2029-03-04Z,"bly, guld, koppar, silver, zink","Västerbottens län, Norrbottens län","Malå kommun, Arvidsjaurs kommun",1478078 BC Ltd (100%),8665,Undersökningstillstånd
823,ut-metaller-industrimineral-beviljade.934,Norra Kärr nr 1,2009:139,139.3812,2009-06-12Z,2009-08-31Z,2009-08-31Z,2026-08-31Z,nefelinsyenit,"Östergötlands län, Jönköpings län","Ödeshögs kommun, Jönköpings kommun",GREENNA Mineral AB (100%),934,Undersökningstillstånd
824,ut-metaller-industrimineral-beviljade.981,Klöverträsk nr 1001,2020:40,1459.0196,2019-12-09Z,2020-04-28Z,2020-04-28Z,2028-04-28Z,"guld, koppar, molybden, silver",Norrbottens län,"Älvsbyns kommun, Piteå kommun",Boliden Mineral AB (100%),981,Undersökningstillstånd
825,ut-metaller-industrimineral-beviljade.985,Björkdal nr 34,2017:162,2520.1587,2017-09-01Z,2017-11-09Z,2017-11-09Z,2029-11-09Z,guld,Västerbottens län,Skellefteå kommun,Björkdalsgruvan AB (100%),985,Undersökningstillstånd
826,ut-metaller-industrimineral-beviljade.99,Jugansbo nr 1007,2020:110,1320.0703,2020-03-18Z,2020-12-16Z,2020-12-16Z,2026-12-16Z,"bly, silver, zink",Västmanlands län,Sala kommun,Boliden Mineral AB (100%),99,Undersökningstillstånd

In [ ]:
# --- List of the columns ---
print(list(df_col_ok.columns))

['id', 'properties.name', 'properties.licenceid', 'properties.area_ha', 'properties.appl_date', 'properties.dec_date', 'properties.validfrom', 'properties.validto', 'properties.mineral', 'properties.county', 'properties.municipal', 'properties.owners', 'properties.permitid', 'properties.permittype']

In [14]:
# --- missing values ---
print(df_col_ok.isna().sum())

id                       0
properties.name          0
properties.licenceid     0
properties.area_ha       0
properties.appl_date     0
properties.dec_date      0
properties.validfrom     0
properties.validto       0
properties.mineral       0
properties.county        0
properties.municipal     0
properties.owners        0
properties.permitid      0
properties.permittype    0
dtype: int64

In [ ]:
# --- QUESTIONS ----
# Top 5 counties to get their premits approved
print(df_col_ok["properties.county"].value_counts().head())

properties.county
Västerbottens län    204
Norrbottens län      203
Dalarnas län          87
Jämtlands län         58
Gävleborgs län        43
Name: count, dtype: int64

In [21]:
# --- The 1rst mineral ---
print(df_col_ok["properties.mineral"].value_counts().head())

properties.mineral
bly, guld, koppar, silver, zink                                              108
järn som förekommer i berggrunden                                             35
guld, koppar, silver, zink                                                    26
lantan och lantanider, molybden, nickel, skandium, vanadin, yttrium, zink     26
guld, koppar                                                                  25
Name: count, dtype: int64